create table flight (
    id bigint generated by default as identity primary key,
    flight_no varchar(20) not null,
    airline_name varchar(64) not null,
    from_city varchar(32) not null,
    to_city varchar(32) not null,
    from_airport varchar(64) not null,
    to_airport varchar(64) not null,
    depart_time timestamp not null,
    arrive_time timestamp not null,
    price decimal(10, 2) not null,
    seats_left int not null default 0,
    data_source varchar(32) not null,
    collected_at timestamp not null
);

create table crawl_job (
    id bigint generated by default as identity primary key,
    status varchar(16) not null,
    started_at timestamp not null,
    finished_at timestamp null,
    success_count int not null default 0,
    failed_count int not null default 0,
    error_message varchar(1000) null,
    source varchar(32) null,
    request_params varchar(500) null
);

create table flight_price_snapshot (
    id bigint generated by default as identity primary key,
    flight_id bigint not null,
    flight_no varchar(20) not null,
    from_city varchar(32) not null,
    to_city varchar(32) not null,
    depart_time timestamp not null,
    price decimal(10, 2) not null,
    seats_left int not null default 0,
    data_source varchar(32) not null,
    observed_at timestamp not null
);

create table flight_validation_failure (
    id bigint generated by default as identity primary key,
    crawl_job_id bigint,
    flight_no varchar(20),
    from_city varchar(32),
    to_city varchar(32),
    depart_time timestamp,
    price decimal(10,2),
    seats_left int,
    failure_reason varchar(500) not null,
    rejected_at timestamp not null
);

create table price_context (
    id bigint generated by default as identity primary key,
    from_city varchar(32) not null,
    to_city varchar(32) not null,
    depart_date date,
    context_text text not null,
    context_type varchar(32) not null default 'PRICE_TREND',
    created_at timestamp not null
);

create table conversation_session (
    id varchar(36) primary key,
    title varchar(128),
    created_at timestamp not null,
    updated_at timestamp not null
);

create table conversation_message (
    id bigint generated by default as identity primary key,
    session_id varchar(36) not null,
    role varchar(16) not null,
    content text not null,
    created_at timestamp not null
);

create table app_user (
    id bigint generated by default as identity primary key,
    username varchar(32) unique not null,
    password varchar(128) not null,
    nickname varchar(32),
    created_at timestamp not null
);

create table user_token (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    token varchar(64) unique not null,
    created_at timestamp not null,
    expires_at timestamp not null
);

create table favorite (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    flight_id bigint not null,
    created_at timestamp not null,
    constraint uk_favorite_user_flight unique (user_id, flight_id),
    constraint fk_favorite_user foreign key (user_id) references app_user(id),
    constraint fk_favorite_flight foreign key (flight_id) references flight(id)
);

create table search_history (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    from_city varchar(32),
    to_city varchar(32),
    travel_date date,
    data_source varchar(32),
    created_at timestamp not null
);
