create table flight (
    id bigint generated by default as identity primary key,
    flight_no varchar(20) not null,
    airline_name varchar(64) not null,
    from_city varchar(32) not null,
    to_city varchar(32) not null,
    from_airport varchar(64) not null,
    to_airport varchar(64) not null,
    depart_time timestamp not null,
    arrive_time timestamp not null,
    price decimal(10, 2) not null,
    seats_left int not null default 0,
    data_source varchar(32) not null,
    collected_at timestamp not null
);

create table crawl_job (
    id bigint generated by default as identity primary key,
    status varchar(16) not null,
    started_at timestamp not null,
    finished_at timestamp null,
    success_count int not null default 0,
    failed_count int not null default 0,
    error_message varchar(1000) null,
    source varchar(32) null,
    actual_source varchar(32) null,
    fallback_reason varchar(500) null,
    request_params varchar(500) null
);

create table flight_price_snapshot (
    id bigint generated by default as identity primary key,
    flight_id bigint not null,
    flight_no varchar(20) not null,
    from_city varchar(32) not null,
    to_city varchar(32) not null,
    depart_time timestamp not null,
    price decimal(10, 2) not null,
    seats_left int not null default 0,
    data_source varchar(32) not null,
    observed_at timestamp not null
);
