create table if not exists flight (
    id bigint generated by default as identity primary key,
    flight_no varchar(20) not null,
    airline_name varchar(64) not null,
    from_city varchar(32) not null,
    to_city varchar(32) not null,
    from_airport varchar(64) not null,
    to_airport varchar(64) not null,
    depart_time timestamp not null,
    arrive_time timestamp not null,
    price decimal(10, 2) not null,
    seats_left int not null default 0,
    data_source varchar(32) not null,
    collected_at timestamp not null
);

create table if not exists crawl_job (
    id bigint generated by default as identity primary key,
    status varchar(16) not null,
    started_at timestamp not null,
    finished_at timestamp null,
    success_count int not null default 0,
    failed_count int not null default 0,
    error_message varchar(1000) null,
    source varchar(32) null,
    request_params varchar(500) null,
    rejected_count int not null default 0
);

create table if not exists flight_price_snapshot (
    id bigint generated by default as identity primary key,
    flight_id bigint not null,
    flight_no varchar(20) not null,
    from_city varchar(32) not null,
    to_city varchar(32) not null,
    depart_time timestamp not null,
    price decimal(10, 2) not null,
    seats_left int not null default 0,
    data_source varchar(32) not null,
    observed_at timestamp not null
);

create table if not exists flight_validation_failure (
    id bigint generated by default as identity primary key,
    crawl_job_id bigint,
    flight_no varchar(20),
    from_city varchar(32),
    to_city varchar(32),
    depart_time timestamp,
    price decimal(10,2),
    seats_left int,
    failure_reason varchar(500) not null,
    rejected_at timestamp not null
);

create table if not exists price_context (
    id bigint generated by default as identity primary key,
    from_city varchar(32) not null,
    to_city varchar(32) not null,
    depart_date date,
    context_text text not null,
    context_type varchar(32) not null default 'PRICE_TREND',
    created_at timestamp not null
);

create table if not exists conversation_session (
    id varchar(36) primary key,
    title varchar(128),
    created_at timestamp not null,
    updated_at timestamp not null
);

create table if not exists conversation_message (
    id bigint generated by default as identity primary key,
    session_id varchar(36) not null,
    role varchar(16) not null,
    content text not null,
    created_at timestamp not null
);

create table if not exists app_user (
    id bigint generated by default as identity primary key,
    username varchar(32) unique not null,
    password varchar(128) not null,
    nickname varchar(32),
    created_at timestamp not null
);

create table if not exists user_token (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    token varchar(64) unique not null,
    created_at timestamp not null,
    expires_at timestamp not null
);

-- Seed sample flights
insert into flight(flight_no, airline_name, from_city, to_city, from_airport, to_airport, depart_time, arrive_time, price, seats_left, data_source, collected_at)
values ('MU5101', '东方航空', '上海', '北京', '虹桥机场', '首都机场', '2026-06-19 08:30:00', '2026-06-19 10:45:00', 980, 12, 'sample', '2026-06-12 09:00:00');
insert into flight(flight_no, airline_name, from_city, to_city, from_airport, to_airport, depart_time, arrive_time, price, seats_left, data_source, collected_at)
values ('CA1502', '中国国航', '上海', '北京', '浦东机场', '大兴机场', '2026-06-19 11:20:00', '2026-06-19 13:35:00', 1280, 8, 'sample', '2026-06-12 09:00:00');
insert into flight(flight_no, airline_name, from_city, to_city, from_airport, to_airport, depart_time, arrive_time, price, seats_left, data_source, collected_at)
values ('CZ3105', '南方航空', '广州', '北京', '白云机场', '大兴机场', '2026-06-19 09:10:00', '2026-06-19 12:10:00', 860, 20, 'sample', '2026-06-12 09:00:00');
insert into flight(flight_no, airline_name, from_city, to_city, from_airport, to_airport, depart_time, arrive_time, price, seats_left, data_source, collected_at)
values ('ZH9103', '深圳航空', '深圳', '上海', '宝安机场', '虹桥机场', '2026-06-20 14:20:00', '2026-06-20 16:35:00', 720, 16, 'sample', '2026-06-12 09:00:00');
insert into flight(flight_no, airline_name, from_city, to_city, from_airport, to_airport, depart_time, arrive_time, price, seats_left, data_source, collected_at)
values ('HU7601', '海南航空', '北京', '上海', '首都机场', '虹桥机场', '2026-06-19 07:00:00', '2026-06-19 09:15:00', 1050, 5, 'sample', '2026-06-12 09:00:00');

-- Seed price snapshots for trend charts
insert into flight_price_snapshot(flight_id, flight_no, from_city, to_city, depart_time, price, seats_left, data_source, observed_at)
values (1, 'MU5101', '上海', '北京', '2026-06-19 08:30:00', 1050, 15, 'sample', '2026-06-10 09:00:00');
insert into flight_price_snapshot(flight_id, flight_no, from_city, to_city, depart_time, price, seats_left, data_source, observed_at)
values (1, 'MU5101', '上海', '北京', '2026-06-19 08:30:00', 1020, 14, 'sample', '2026-06-11 09:00:00');
insert into flight_price_snapshot(flight_id, flight_no, from_city, to_city, depart_time, price, seats_left, data_source, observed_at)
values (1, 'MU5101', '上海', '北京', '2026-06-19 08:30:00', 980, 12, 'sample', '2026-06-12 09:00:00');

-- Seed a crawl job for dashboard
insert into crawl_job(status, started_at, finished_at, success_count, failed_count, error_message, source, request_params, rejected_count)
values ('SUCCESS', '2026-06-12 09:00:00', '2026-06-12 09:00:05', 5, 0, null, 'sample', 'source=sample, fromCity=上海, toCity=北京, date=2026-06-19', 0);
